[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.144"
chrono = "0.4"
flume = "0.10.14"

[dependencies.uuid]
uuid = "1.1.2"
features = ["v4"]
